// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBVTPs-VNro2PdaQ5vtChJUfJvaoK87Ws',
    appId: '1:725738310524:web:4d798f07aa0755650bb2f9',
    messagingSenderId: '725738310524',
    projectId: 'gelirgider-7c63c',
    authDomain: 'gelirgider-7c63c.firebaseapp.com',
    storageBucket: 'gelirgider-7c63c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuh9YajFJM206ybpQSOvnxTv4ZVgi5X1U',
    appId: '1:725738310524:android:561e55d4d9de42580bb2f9',
    messagingSenderId: '725738310524',
    projectId: 'gelirgider-7c63c',
    storageBucket: 'gelirgider-7c63c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD68rSv_2nXBGihKABOvsRhoyINuJWncxo',
    appId: '1:725738310524:ios:1bfb55f7f7a2c41e0bb2f9',
    messagingSenderId: '725738310524',
    projectId: 'gelirgider-7c63c',
    storageBucket: 'gelirgider-7c63c.firebasestorage.app',
    iosBundleId: 'com.example.gelirgider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD68rSv_2nXBGihKABOvsRhoyINuJWncxo',
    appId: '1:725738310524:ios:1bfb55f7f7a2c41e0bb2f9',
    messagingSenderId: '725738310524',
    projectId: 'gelirgider-7c63c',
    storageBucket: 'gelirgider-7c63c.firebasestorage.app',
    iosBundleId: 'com.example.gelirgider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBVTPs-VNro2PdaQ5vtChJUfJvaoK87Ws',
    appId: '1:725738310524:web:1b509a3f47f78f7a0bb2f9',
    messagingSenderId: '725738310524',
    projectId: 'gelirgider-7c63c',
    authDomain: 'gelirgider-7c63c.firebaseapp.com',
    storageBucket: 'gelirgider-7c63c.firebasestorage.app',
  );
}
